name: shimmer_fade
description: "A package provides an easy way to add a shimmer effect similar to what you see on Facebook or Netflix. It's super fast, lightweight, and easy to set up."
version: 0.0.1
repository: https://github.com/hoangdinhphi92/shimmer_fade
issue_tracker: https://github.com/hoangdinhphi92/shimmer_fade/issues
homepage: https://github.com/hoangdinhphi92/shimmer_fade

environment:
  sdk: ^3.5.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
